name: Build artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ci

jobs:
  build-artifacts:
    name: Build artifacts
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Install Deps
        run: |
          sudo apt update
          sudo apt install -yy build-essential clang brotli binaryen ninja-build gcc-multilib
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install wasmtime
        run: cargo install wasmtime-cli
      - name: Test wasmtime installation
        run: which wasmtime
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install wasm32-wasip1-threads Rust target
        run: rustup target add wasm32-wasip1-threads
      - name: Build Ruff
        run: make build/ruff.BUILT
      - name: Build host tools
        run: make build/llvm-host.BUILT
      - name: Build C++ compiler
        run: make build/llvm.BUILT
      - name: Build Python
        run: make build/python.BUILT
      - name: Finalize build
        run: make
      - name: Upload built compilers
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: compilers
          path: build/output/*.tar.br
          compression-level: 0
